uav_parameters:
  mass: 1.725
  arm_length: 0.343;    #xyz = 0.13 -0.22 0.023
  inertia:
    x: 0.029125
    y: 0.029125
    z: 0.055225
  #kMomentConstant: 1.6e-2
  #kThrustConstant: 8.568e-6
  gravity: 9.81
  max_roll_torque: 1.8373
  max_pitch_torque: 3.1092
  max_yaw_torque: 1         # place-holder
  max_thrust: 28.2656
# How to get the max values?
# run this Matlab script while changing:
#     K_motor, K_moment, max_vel
# Matlab Script:
#  %   From iris.sdf
#  x_position = 0.13;
#  y_position = 0.22;
#  K_motor = 5.84e-06;
#  K_moment = 0.06;
#  max_vel = 1100;     % rad/s
#  max_force = K_motor * (max_vel^2)
#  max_x_torque = 2 * max_force * x_position
#  max_y_torque = 2 * max_force * y_position
#  max_thrust = 4 * max_force
#  max_yaw_torque = 4 * K_moment * max_force