uav_parameters:
  mass: 3.506          #2.534 + 0.015 IMU + 0.0474 6 motors
  arm_length: 0.343;    #xyz = 0.13 -0.22 0.023
  inertia:
    x: 0.11704605
    y: 0.09738435
    z: 0.18810260
  #kMomentConstant: 1.6e-2
  #kThrustConstant: 8.568e-6
  gravity: 9.81
  max_roll_torque: 7.0845
  max_pitch_torque:  6.1359
  max_yaw_torque: 1         # place-holder
  max_thrust: 62.0627