uav_parameters:
  mass: 3.506          #2.534 + 0.015 IMU + 0.0474 6 motors
  arm_length: 0.343;    #xyz = 0.13 -0.22 0.023
  inertia:
    x: 0.11704605
    y: 0.09738435
    z: 0.18810260
  #kMomentConstant: 1.6e-2
  #kThrustConstant: 8.568e-6
  gravity: 9.81
  # TODO move this calculation to the controller class
  max_roll_torque: 13.1736
  max_pitch_torque:  11.4098
  max_yaw_torque: 1         # place-holder, not correct
  max_thrust: 115.4058
# How to get the max values?
# run this Matlab script with changing:
#     (K_motor, K_moment, max_vel) in accordance to what you have in SDF file
# and (x_position, y_position, arm) (of the propellers) for your UAV specific configuration
# Matlab Script:
#  %   From peach.sdf
#  x_position = 0.2966;                 % Absolute displacement of the 4 propellers in x-axis (hex-x configuration)
#  y_position = 0.1712;                 % Absolute displacement of the 4 propellers in y-axis (hex-x configuration)
#  arm = 0.3425;                        % Euclidean displacement of the propellers from COM
#  K_motor = 8.54858e-06;               % motorConstant from sdf
#  K_moment = 0.06;                     % momentConstant from sdf
#  max_vel = 1500;                      % [rad/s] maxRotVelocity from sdf
#  max_force = K_motor * (max_vel^2)    % from Tools/sitl_gazebo/src/gazebo_motor_model.cpp
#
#  max_x_torque = (2 * max_force * y_position ) + (max_force * arm)
#  max_y_torque = 2 * max_force * x_position
#  max_thrust = 6 * max_force
#  max_yaw_torque = 6 * K_moment * max_force % not correct